### ISSUE TITLE
Enable to integrate the smarthand with panda Emika arm vis ROS

### ISSUE THREAD

**Issue by amranov** [RoboticMaterials/rmlib#1]
Hi guys, 
I am using an XML-RPCserver to receive go-to-pose command from the hand, and now i am trying to issue this command to moveit. 
is it the right way to control arm and hand ? 
is there any other way to import the hand via ROS ? (kinetic 16.04)
regards

**Comment by correll** [comment]
XML-RPC server is definitely the way to go to send and receive commands. There exists a XML-RPC server binding for ROS (http://wiki.ros.org/xmlrpcpp), which could run on the server running MoveIt! and translate data and commands.
